-- Supabase Database Schema

-- 1. Create Users Table
CREATE TABLE public."Users" (
    id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name text,
    email text,
    role text CHECK (role IN ('Author', 'Viewer', 'Admin')),
    PRIMARY KEY (id)
);

-- 2. Create Posts Table
CREATE TABLE public."Posts" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    body text NOT NULL,
    image_url text,
    author_id uuid REFERENCES public."Users"(id) ON DELETE CASCADE,
    summary text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Comments Table
CREATE TABLE public."Comments" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint REFERENCES public."Posts"(id) ON DELETE CASCADE,
    user_id uuid REFERENCES public."Users"(id) ON DELETE CASCADE,
    comment_text text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Simple Row Level Security (RLS) setup 
-- Enable RLS
ALTER TABLE public."Users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Posts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Comments" ENABLE ROW LEVEL SECURITY;

-- Allow public read access (for basic platform requirements)
CREATE POLICY "Public profiles are viewable by everyone." ON public."Users" FOR SELECT USING (true);
CREATE POLICY "Public posts are viewable by everyone." ON public."Posts" FOR SELECT USING (true);
CREATE POLICY "Public comments are viewable by everyone." ON public."Comments" FOR SELECT USING (true);

-- Allow authenticated users to insert/update based on roles
CREATE POLICY "Users can insert their own profile." ON public."Users" FOR INSERT WITH CHECK (auth.uid() = id);

-- Authors and Admins can insert posts
CREATE POLICY "Authors and Admins can insert posts" ON public."Posts" FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public."Users"
    WHERE "Users".id = auth.uid() AND ("Users".role = 'Author' OR "Users".role = 'Admin')
  )
);

-- Allow Authors to update their own posts, Admins to update all
CREATE POLICY "Authors can update own posts, Admins everything" ON public."Posts" FOR UPDATE USING (
  auth.uid() = author_id OR 
  EXISTS (SELECT 1 FROM public."Users" WHERE "Users".id = auth.uid() AND "Users".role = 'Admin')
);

-- Allow any authenticated user to comment
CREATE POLICY "Authenticated users can comment" ON public."Comments" FOR INSERT WITH CHECK (auth.uid() = user_id);

-- trigger to insert user profile on signup
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public."Users" (id, email, name, role)
  values (new.id, new.email, split_part(new.email, '@', 1), 'Viewer');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
